version: '3.8'

services:
  flowershop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowershop-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app       # mount current project for hot reload
      - /app/node_modules # prevent node_modules overwrite